"""正本・ロック・つなぎ先・順番待ち・閾値

Revision ID: 95da9a07a59b
Revises: 
Create Date: 2026-10-07 23:41:43.812248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '95da9a07a59b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('services',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=8), nullable=False),
    sa.Column('location', sa.String(length=8), nullable=False),
    sa.Column('adapter', sa.String(length=16), nullable=False),
    sa.Column('endpoint', sa.Text(), nullable=True),
    sa.Column('send_mode', sa.String(length=8), nullable=False),
    sa.Column('max_concurrency', sa.Integer(), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('paused', sa.Boolean(), nullable=False),
    sa.Column('monthly_budget', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('system_values',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('works',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('reading_direction', sa.String(length=8), nullable=False),
    sa.Column('text_direction', sa.String(length=16), nullable=False),
    sa.Column('medium', sa.String(length=32), nullable=False),
    sa.Column('trim_size', sa.String(length=32), nullable=True),
    sa.Column('default_page_count', sa.Integer(), nullable=True),
    sa.Column('head_seq', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('seq', sa.BigInteger(), nullable=False),
    sa.Column('actor_kind', sa.String(length=8), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('on_behalf_of', sa.String(length=128), nullable=True),
    sa.Column('op_type', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('inverse', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('undoes_event_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['undoes_event_id'], ['events.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_id', 'seq')
    )
    op.create_index(op.f('ix_events_work_id'), 'events', ['work_id'], unique=False)
    op.create_table('finding_reactions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('finding_key', sa.String(length=128), nullable=False),
    sa.Column('target_kind', sa.String(length=8), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('reaction', sa.String(length=16), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_finding_reactions_work_id'), 'finding_reactions', ['work_id'], unique=False)
    op.create_table('process_routes',
    sa.Column('process', sa.String(length=64), nullable=False),
    sa.Column('service_id', sa.String(length=32), nullable=False),
    sa.Column('resend_limit', sa.Integer(), nullable=False),
    sa.Column('regenerate_limit', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('process')
    )
    op.create_table('service_processes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('service_id', sa.String(length=32), nullable=False),
    sa.Column('process', sa.String(length=64), nullable=False),
    sa.Column('aptitude', sa.String(length=8), nullable=True),
    sa.Column('cost_per_call', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('comfy_workflow', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('service_id', 'process')
    )
    op.create_index(op.f('ix_service_processes_service_id'), 'service_processes', ['service_id'], unique=False)
    op.create_table('thresholds',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('key', sa.String(length=128), nullable=False),
    sa.Column('value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_id', 'key')
    )
    op.create_index(op.f('ix_thresholds_work_id'), 'thresholds', ['work_id'], unique=False)
    op.create_table('volumes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_volumes_work_id'), 'volumes', ['work_id'], unique=False)
    op.create_table('work_destinations',
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('service_id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('work_id', 'service_id')
    )
    op.create_table('episodes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('volume_id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('title', sa.Text(), nullable=True),
    sa.Column('deadline', sa.DateTime(timezone=True), nullable=True),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['volume_id'], ['volumes.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_episodes_volume_id'), 'episodes', ['volume_id'], unique=False)
    op.create_index(op.f('ix_episodes_work_id'), 'episodes', ['work_id'], unique=False)
    op.create_table('pages',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('episode_id', sa.String(length=32), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pages_episode_id'), 'pages', ['episode_id'], unique=False)
    op.create_index(op.f('ix_pages_work_id'), 'pages', ['work_id'], unique=False)
    op.create_table('jobs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('service_id', sa.String(length=32), nullable=False),
    sa.Column('process', sa.String(length=64), nullable=False),
    sa.Column('page_id', sa.String(length=32), nullable=True),
    sa.Column('requested_by', sa.String(length=128), nullable=False),
    sa.Column('requested_via', sa.String(length=8), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('failure_kind', sa.String(length=32), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('request', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('result', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('workflow_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jobs_service_id'), 'jobs', ['service_id'], unique=False)
    op.create_index(op.f('ix_jobs_work_id'), 'jobs', ['work_id'], unique=False)
    op.create_table('locks',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('target_kind', sa.String(length=8), nullable=False),
    sa.Column('target_id', sa.String(length=64), nullable=False),
    sa.Column('page_id', sa.String(length=32), nullable=False),
    sa.Column('holder_kind', sa.String(length=8), nullable=False),
    sa.Column('holder_id', sa.String(length=128), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_kind', 'target_id')
    )
    op.create_index(op.f('ix_locks_page_id'), 'locks', ['page_id'], unique=False)
    op.create_index(op.f('ix_locks_work_id'), 'locks', ['work_id'], unique=False)
    op.create_table('panels',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('page_id', sa.String(length=32), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('frame', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=True),
    sa.Column('content', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('human_confirmed', sa.Boolean(), nullable=False),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panels_page_id'), 'panels', ['page_id'], unique=False)
    op.create_index(op.f('ix_panels_work_id'), 'panels', ['work_id'], unique=False)
    op.create_table('call_logs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('service_id', sa.String(length=32), nullable=False),
    sa.Column('attempt', sa.Integer(), nullable=False),
    sa.Column('model', sa.Text(), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('seed', sa.BigInteger(), nullable=True),
    sa.Column('tokens_in', sa.Integer(), nullable=True),
    sa.Column('tokens_out', sa.Integer(), nullable=True),
    sa.Column('cost', sa.Numeric(precision=12, scale=4), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('outcome', sa.String(length=8), nullable=False),
    sa.Column('failure_kind', sa.String(length=32), nullable=True),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_call_logs_job_id'), 'call_logs', ['job_id'], unique=False)
    op.create_index(op.f('ix_call_logs_work_id'), 'call_logs', ['work_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_call_logs_work_id'), table_name='call_logs')
    op.drop_index(op.f('ix_call_logs_job_id'), table_name='call_logs')
    op.drop_table('call_logs')
    op.drop_index(op.f('ix_panels_work_id'), table_name='panels')
    op.drop_index(op.f('ix_panels_page_id'), table_name='panels')
    op.drop_table('panels')
    op.drop_index(op.f('ix_locks_work_id'), table_name='locks')
    op.drop_index(op.f('ix_locks_page_id'), table_name='locks')
    op.drop_table('locks')
    op.drop_index(op.f('ix_jobs_work_id'), table_name='jobs')
    op.drop_index(op.f('ix_jobs_service_id'), table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_pages_work_id'), table_name='pages')
    op.drop_index(op.f('ix_pages_episode_id'), table_name='pages')
    op.drop_table('pages')
    op.drop_index(op.f('ix_episodes_work_id'), table_name='episodes')
    op.drop_index(op.f('ix_episodes_volume_id'), table_name='episodes')
    op.drop_table('episodes')
    op.drop_table('work_destinations')
    op.drop_index(op.f('ix_volumes_work_id'), table_name='volumes')
    op.drop_table('volumes')
    op.drop_index(op.f('ix_thresholds_work_id'), table_name='thresholds')
    op.drop_table('thresholds')
    op.drop_index(op.f('ix_service_processes_service_id'), table_name='service_processes')
    op.drop_table('service_processes')
    op.drop_table('process_routes')
    op.drop_index(op.f('ix_finding_reactions_work_id'), table_name='finding_reactions')
    op.drop_table('finding_reactions')
    op.drop_index(op.f('ix_events_work_id'), table_name='events')
    op.drop_table('events')
    op.drop_table('works')
    op.drop_table('system_values')
    op.drop_table('services')
    # ### end Alembic commands ###
