"""人とAIのどちらでも作れる：ネームの案・絵のファイル・人の手の印

Revision ID: 0002
Revises: 95da9a07a59b
Create Date: 2026-10-08 00:41:45.022162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0002'
down_revision: Union[str, Sequence[str], None] = '95da9a07a59b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_files',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('page_id', sa.String(length=32), nullable=True),
    sa.Column('panel_id', sa.String(length=32), nullable=True),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('origin', sa.String(length=16), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('source_note', sa.Text(), nullable=True),
    sa.Column('registered_by_kind', sa.String(length=8), nullable=False),
    sa.Column('registered_by_id', sa.String(length=128), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('media_type', sa.String(length=64), nullable=False),
    sa.Column('width', sa.Integer(), nullable=False),
    sa.Column('height', sa.Integer(), nullable=False),
    sa.Column('dpi', sa.Integer(), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_files_page_id'), 'image_files', ['page_id'], unique=False)
    op.create_index(op.f('ix_image_files_panel_id'), 'image_files', ['panel_id'], unique=False)
    op.create_index(op.f('ix_image_files_sha256'), 'image_files', ['sha256'], unique=False)
    op.create_index(op.f('ix_image_files_work_id'), 'image_files', ['work_id'], unique=False)
    op.create_table('name_proposals',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('episode_id', sa.String(length=32), nullable=False),
    sa.Column('made_by', sa.String(length=16), nullable=False),
    sa.Column('submitted_by_kind', sa.String(length=8), nullable=False),
    sa.Column('submitted_by_id', sa.String(length=128), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('pages', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_name_proposals_episode_id'), 'name_proposals', ['episode_id'], unique=False)
    op.create_index(op.f('ix_name_proposals_work_id'), 'name_proposals', ['work_id'], unique=False)
    op.add_column('pages', sa.Column('layout', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default=sa.text("'{}'")))
    op.add_column('pages', sa.Column('human_hand_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default=sa.text("'[]'")))
    op.add_column('panels', sa.Column('image_id', sa.String(length=32), nullable=True))
    op.add_column('panels', sa.Column('human_hand_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False, server_default=sa.text("'[]'")))
    op.create_foreign_key('panels_image_id_fkey', 'panels', 'image_files', ['image_id'], ['id'])
    op.add_column('works', sa.Column('first_page_is_left', sa.Boolean(), nullable=True))
    op.add_column('works', sa.Column('page_spec', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'page_spec')
    op.drop_column('works', 'first_page_is_left')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('panels_image_id_fkey', 'panels', type_='foreignkey')
    op.drop_column('panels', 'human_hand_fields')
    op.drop_column('panels', 'image_id')
    op.drop_column('pages', 'human_hand_fields')
    op.drop_column('pages', 'layout')
    op.drop_index(op.f('ix_name_proposals_work_id'), table_name='name_proposals')
    op.drop_index(op.f('ix_name_proposals_episode_id'), table_name='name_proposals')
    op.drop_table('name_proposals')
    op.drop_index(op.f('ix_image_files_work_id'), table_name='image_files')
    op.drop_index(op.f('ix_image_files_sha256'), table_name='image_files')
    op.drop_index(op.f('ix_image_files_panel_id'), table_name='image_files')
    op.drop_index(op.f('ix_image_files_page_id'), table_name='image_files')
    op.drop_table('image_files')
    # ### end Alembic commands ###
