"""ネームの検査の記録

Revision ID: 0004
Revises: 0003
Create Date: 2026-10-08 00:53:02.129896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0004'
down_revision: Union[str, Sequence[str], None] = '0003'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('name_check_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('episode_id', sa.String(length=32), nullable=False),
    sa.Column('proposal_id', sa.String(length=32), nullable=True),
    sa.Column('run_by_kind', sa.String(length=8), nullable=False),
    sa.Column('run_by_id', sa.String(length=128), nullable=False),
    sa.Column('thresholds_used', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('report', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['name_proposals.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_name_check_runs_episode_id'), 'name_check_runs', ['episode_id'], unique=False)
    op.create_index(op.f('ix_name_check_runs_work_id'), 'name_check_runs', ['work_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_name_check_runs_work_id'), table_name='name_check_runs')
    op.drop_index(op.f('ix_name_check_runs_episode_id'), table_name='name_check_runs')
    op.drop_table('name_check_runs')
    # ### end Alembic commands ###
