"""人とAIの受け渡し：AIの関与・文字・層・人の手の範囲・判断待ち・絵の版と条件・入口の判定

Revision ID: 0005
Revises: 0004
Create Date: 2026-10-08 01:21:36.353050

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0005'
down_revision: str | Sequence[str] | None = '0004'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('image_intake_screenings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('sha256', sa.String(length=64), nullable=False),
    sa.Column('entry', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('judge', sa.Text(), nullable=True),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_image_intake_screenings_sha256'), 'image_intake_screenings', ['sha256'], unique=False)
    op.create_index(op.f('ix_image_intake_screenings_work_id'), 'image_intake_screenings', ['work_id'], unique=False)
    op.create_table('panel_layers',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('page_id', sa.String(length=32), nullable=False),
    sa.Column('panel_id', sa.String(length=32), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('image_id', sa.String(length=32), nullable=True),
    sa.Column('stack_order', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('opacity', sa.Float(), nullable=False),
    sa.Column('placement', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('human_hand_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image_files.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panel_layers_page_id'), 'panel_layers', ['page_id'], unique=False)
    op.create_index(op.f('ix_panel_layers_panel_id'), 'panel_layers', ['panel_id'], unique=False)
    op.create_index(op.f('ix_panel_layers_work_id'), 'panel_layers', ['work_id'], unique=False)
    op.create_table('protected_regions',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('image_id', sa.String(length=32), nullable=False),
    sa.Column('page_id', sa.String(length=32), nullable=True),
    sa.Column('polygon_px', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image_files.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_protected_regions_image_id'), 'protected_regions', ['image_id'], unique=False)
    op.create_index(op.f('ix_protected_regions_page_id'), 'protected_regions', ['page_id'], unique=False)
    op.create_index(op.f('ix_protected_regions_work_id'), 'protected_regions', ['work_id'], unique=False)
    op.create_table('text_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('page_id', sa.String(length=32), nullable=False),
    sa.Column('panel_id', sa.String(length=32), nullable=False),
    sa.Column('item_kind', sa.String(length=16), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('speaker', sa.Text(), nullable=True),
    sa.Column('balloon_kind', sa.String(length=16), nullable=True),
    sa.Column('writing_direction', sa.String(length=16), nullable=True),
    sa.Column('font_size_pt', sa.Float(), nullable=True),
    sa.Column('box_mm', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('tail_target_mm', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('joined_to_previous', sa.Boolean(), nullable=True),
    sa.Column('human_hand_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_text_items_page_id'), 'text_items', ['page_id'], unique=False)
    op.create_index(op.f('ix_text_items_panel_id'), 'text_items', ['panel_id'], unique=False)
    op.create_index(op.f('ix_text_items_work_id'), 'text_items', ['work_id'], unique=False)
    op.create_table('held_ai_changes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('target_table', sa.String(length=16), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=False),
    sa.Column('page_id', sa.String(length=32), nullable=False),
    sa.Column('field', sa.String(length=32), nullable=False),
    sa.Column('proposed_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('current_value', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('proposal_id', sa.String(length=32), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['proposal_id'], ['name_proposals.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_held_ai_changes_page_id'), 'held_ai_changes', ['page_id'], unique=False)
    op.create_index(op.f('ix_held_ai_changes_work_id'), 'held_ai_changes', ['work_id'], unique=False)
    op.add_column('image_files', sa.Column('based_on_image_id', sa.String(length=32), nullable=True))
    op.add_column('image_files', sa.Column('usage_terms', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.create_index(op.f('ix_image_files_based_on_image_id'), 'image_files', ['based_on_image_id'], unique=False)
    op.create_foreign_key('fk_image_files_based_on_image_id', 'image_files', 'image_files', ['based_on_image_id'], ['id'])
    op.add_column('name_proposals', sa.Column('task', sa.String(length=16), server_default='name', nullable=False))
    op.add_column('name_proposals', sa.Column('source_document', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('panels', sa.Column('image_placement', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('process_routes', sa.Column('ai_task', sa.String(length=32), nullable=True))
    op.add_column('process_routes', sa.Column('ai_action', sa.String(length=8), nullable=True))
    op.add_column('services', sa.Column('usage_terms', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('works', sa.Column('ai_involvement', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'ai_involvement')
    op.drop_column('services', 'usage_terms')
    op.drop_column('process_routes', 'ai_action')
    op.drop_column('process_routes', 'ai_task')
    op.drop_column('panels', 'image_placement')
    op.drop_column('name_proposals', 'source_document')
    op.drop_column('name_proposals', 'task')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint('fk_image_files_based_on_image_id', 'image_files', type_='foreignkey')
    op.drop_index(op.f('ix_image_files_based_on_image_id'), table_name='image_files')
    op.drop_column('image_files', 'usage_terms')
    op.drop_column('image_files', 'based_on_image_id')
    op.drop_index(op.f('ix_held_ai_changes_work_id'), table_name='held_ai_changes')
    op.drop_index(op.f('ix_held_ai_changes_page_id'), table_name='held_ai_changes')
    op.drop_table('held_ai_changes')
    op.drop_index(op.f('ix_text_items_work_id'), table_name='text_items')
    op.drop_index(op.f('ix_text_items_panel_id'), table_name='text_items')
    op.drop_index(op.f('ix_text_items_page_id'), table_name='text_items')
    op.drop_table('text_items')
    op.drop_index(op.f('ix_protected_regions_work_id'), table_name='protected_regions')
    op.drop_index(op.f('ix_protected_regions_page_id'), table_name='protected_regions')
    op.drop_index(op.f('ix_protected_regions_image_id'), table_name='protected_regions')
    op.drop_table('protected_regions')
    op.drop_index(op.f('ix_panel_layers_work_id'), table_name='panel_layers')
    op.drop_index(op.f('ix_panel_layers_panel_id'), table_name='panel_layers')
    op.drop_index(op.f('ix_panel_layers_page_id'), table_name='panel_layers')
    op.drop_table('panel_layers')
    op.drop_index(op.f('ix_image_intake_screenings_work_id'), table_name='image_intake_screenings')
    op.drop_index(op.f('ix_image_intake_screenings_sha256'), table_name='image_intake_screenings')
    op.drop_table('image_intake_screenings')
    # ### end Alembic commands ###
