"""人が直す道具・置き方・仕上げ・企画と設定資料・設定・書き出し

Revision ID: 0006
Revises: 0005
Create Date: 2026-10-08 01:52:42.354181

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0006'
down_revision: Union[str, Sequence[str], None] = '0005'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_settings',
    sa.Column('user_id', sa.String(length=128), nullable=False),
    sa.Column('language', sa.String(length=16), nullable=True),
    sa.Column('autosave', sa.Boolean(), nullable=True),
    sa.Column('autosave_interval_seconds', sa.Integer(), nullable=True),
    sa.Column('other', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('export_runs',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('requested_by', sa.String(length=128), nullable=False),
    sa.Column('format', sa.String(length=8), nullable=False),
    sa.Column('page_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('dpi', sa.Integer(), nullable=False),
    sa.Column('paper_mm', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('detail', sa.Text(), nullable=True),
    sa.Column('outputs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('workflow_id', sa.String(length=128), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_export_runs_work_id'), 'export_runs', ['work_id'], unique=False)
    op.create_table('panel_templates',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('frames', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('human_hand_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_panel_templates_work_id'), 'panel_templates', ['work_id'], unique=False)
    op.create_table('work_plans',
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('synopsis', sa.Text(), nullable=True),
    sa.Column('audience', sa.Text(), nullable=True),
    sa.Column('exclusions', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('human_hand_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('work_id')
    )
    op.create_table('annotation_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('page_id', sa.String(length=32), nullable=False),
    sa.Column('panel_id', sa.String(length=32), nullable=True),
    sa.Column('region_mm', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('about_task', sa.String(length=32), nullable=False),
    sa.Column('author_kind', sa.String(length=8), nullable=False),
    sa.Column('author_id', sa.String(length=128), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('job_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('human_hand_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_annotation_items_page_id'), 'annotation_items', ['page_id'], unique=False)
    op.create_index(op.f('ix_annotation_items_panel_id'), 'annotation_items', ['panel_id'], unique=False)
    op.create_index(op.f('ix_annotation_items_work_id'), 'annotation_items', ['work_id'], unique=False)
    op.create_table('page_items',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('page_id', sa.String(length=32), nullable=False),
    sa.Column('panel_id', sa.String(length=32), nullable=True),
    sa.Column('item_kind', sa.String(length=16), nullable=False),
    sa.Column('spec', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('box_mm', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('transform', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stack_order', sa.Integer(), nullable=False),
    sa.Column('visible', sa.Boolean(), nullable=False),
    sa.Column('opacity', sa.Float(), nullable=False),
    sa.Column('adjustments', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('fixed', sa.Boolean(), nullable=False),
    sa.Column('human_hand_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_items_page_id'), 'page_items', ['page_id'], unique=False)
    op.create_index(op.f('ix_page_items_panel_id'), 'page_items', ['panel_id'], unique=False)
    op.create_index(op.f('ix_page_items_work_id'), 'page_items', ['work_id'], unique=False)
    op.create_table('material_entries',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('kind', sa.String(length=16), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('traits', sa.Text(), nullable=True),
    sa.Column('clothes', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('image_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('generation', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('proposal_state', sa.String(length=16), nullable=False),
    sa.Column('job_id', sa.String(length=32), nullable=True),
    sa.Column('human_hand_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_material_entries_work_id'), 'material_entries', ['work_id'], unique=False)
    op.create_table('pen_strokes',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('page_id', sa.String(length=32), nullable=False),
    sa.Column('panel_id', sa.String(length=32), nullable=False),
    sa.Column('layer_id', sa.String(length=32), nullable=False),
    sa.Column('brush', sa.String(length=24), nullable=False),
    sa.Column('points', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('width_mm', sa.Float(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('opacity', sa.Float(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=True),
    sa.Column('brush_options', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('stack_order', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('fixed', sa.Boolean(), nullable=False),
    sa.Column('human_hand_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['layer_id'], ['panel_layers.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pen_strokes_layer_id'), 'pen_strokes', ['layer_id'], unique=False)
    op.create_index(op.f('ix_pen_strokes_page_id'), 'pen_strokes', ['page_id'], unique=False)
    op.create_index(op.f('ix_pen_strokes_panel_id'), 'pen_strokes', ['panel_id'], unique=False)
    op.create_index(op.f('ix_pen_strokes_work_id'), 'pen_strokes', ['work_id'], unique=False)
    op.add_column('held_ai_changes', sa.Column('kind', sa.String(length=32), server_default='field_change', nullable=False))
    op.add_column('held_ai_changes', sa.Column('choices', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('held_ai_changes', sa.Column('chosen', sa.String(length=32), nullable=True))
    op.add_column('held_ai_changes', sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.alter_column('held_ai_changes', 'page_id', existing_type=sa.String(length=32), nullable=True)
    op.alter_column('held_ai_changes', 'target_table',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.String(length=32),
               existing_nullable=False)
    op.alter_column('held_ai_changes', 'field',
               existing_type=sa.VARCHAR(length=32),
               type_=sa.String(length=64),
               existing_nullable=False)
    op.add_column('panel_layers', sa.Column('adjustments', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('panel_layers', sa.Column('fixed', sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column('panel_layers', sa.Column('stroke_revision', sa.Integer(), server_default='0', nullable=False))
    op.add_column('panel_layers', sa.Column('image_stroke_revision', sa.Integer(), nullable=True))
    op.add_column('panels', sa.Column('frame_style', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('panels', sa.Column('adjustments', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('panels', sa.Column('fixed', sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column('protected_regions', sa.Column('mask_sha256', sa.String(length=64), nullable=True))
    op.alter_column('protected_regions', 'polygon_px',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.add_column('text_items', sa.Column('font_family', sa.Text(), nullable=True))
    op.add_column('text_items', sa.Column('decoration', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('text_items', sa.Column('ruby', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('text_items', sa.Column('balloon_shape', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=True))
    op.add_column('text_items', sa.Column('transform', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False))
    op.add_column('text_items', sa.Column('opacity', sa.Float(), server_default=sa.text("1"), nullable=False))
    op.add_column('text_items', sa.Column('adjustments', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'[]'"), nullable=False))
    op.add_column('text_items', sa.Column('fixed', sa.Boolean(), server_default=sa.text("false"), nullable=False))
    op.add_column('works', sa.Column('preferences', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default=sa.text("'{}'"), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('works', 'preferences')
    op.drop_column('text_items', 'fixed')
    op.drop_column('text_items', 'adjustments')
    op.drop_column('text_items', 'opacity')
    op.drop_column('text_items', 'transform')
    op.drop_column('text_items', 'balloon_shape')
    op.drop_column('text_items', 'ruby')
    op.drop_column('text_items', 'decoration')
    op.drop_column('text_items', 'font_family')
    # マスクで持つ範囲は前の形に入らないので消す
    op.execute("DELETE FROM protected_regions WHERE polygon_px IS NULL")
    op.alter_column('protected_regions', 'polygon_px',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.drop_column('protected_regions', 'mask_sha256')
    op.drop_column('panels', 'fixed')
    op.drop_column('panels', 'adjustments')
    op.drop_column('panels', 'frame_style')
    op.drop_column('panel_layers', 'image_stroke_revision')
    op.drop_column('panel_layers', 'stroke_revision')
    op.drop_column('panel_layers', 'fixed')
    op.drop_column('panel_layers', 'adjustments')
    # 前の形に入らない判断待ち（項目の変更以外）は消す
    op.execute("DELETE FROM held_ai_changes WHERE kind <> 'field_change' OR page_id IS NULL")
    op.alter_column('held_ai_changes', 'page_id', existing_type=sa.String(length=32), nullable=False)
    op.alter_column('held_ai_changes', 'field',
               existing_type=sa.String(length=64),
               type_=sa.VARCHAR(length=32),
               existing_nullable=False)
    op.alter_column('held_ai_changes', 'target_table',
               existing_type=sa.String(length=32),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)
    op.drop_column('held_ai_changes', 'payload')
    op.drop_column('held_ai_changes', 'chosen')
    op.drop_column('held_ai_changes', 'choices')
    op.drop_column('held_ai_changes', 'kind')
    op.drop_index(op.f('ix_pen_strokes_work_id'), table_name='pen_strokes')
    op.drop_index(op.f('ix_pen_strokes_panel_id'), table_name='pen_strokes')
    op.drop_index(op.f('ix_pen_strokes_page_id'), table_name='pen_strokes')
    op.drop_index(op.f('ix_pen_strokes_layer_id'), table_name='pen_strokes')
    op.drop_table('pen_strokes')
    op.drop_index(op.f('ix_material_entries_work_id'), table_name='material_entries')
    op.drop_table('material_entries')
    op.drop_index(op.f('ix_page_items_work_id'), table_name='page_items')
    op.drop_index(op.f('ix_page_items_panel_id'), table_name='page_items')
    op.drop_index(op.f('ix_page_items_page_id'), table_name='page_items')
    op.drop_table('page_items')
    op.drop_index(op.f('ix_annotation_items_work_id'), table_name='annotation_items')
    op.drop_index(op.f('ix_annotation_items_panel_id'), table_name='annotation_items')
    op.drop_index(op.f('ix_annotation_items_page_id'), table_name='annotation_items')
    op.drop_table('annotation_items')
    op.drop_table('work_plans')
    op.drop_index(op.f('ix_panel_templates_work_id'), table_name='panel_templates')
    op.drop_table('panel_templates')
    op.drop_index(op.f('ix_export_runs_work_id'), table_name='export_runs')
    op.drop_table('export_runs')
    op.drop_table('user_settings')
    # ### end Alembic commands ###
