"""今のアプリからの移行（取り込みの報告・コマと絵ごとのAIの設定）、文字の言語ごとの版、承認の状態と記録、書き出しの言語

Revision ID: 0011
Revises: 0010
Create Date: 2026-10-08 14:00:00

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0011'
down_revision: str | Sequence[str] | None = '0010'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('review_records',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('target_kind', sa.String(length=8), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=False),
    sa.Column('from_status', sa.String(length=16), nullable=False),
    sa.Column('to_status', sa.String(length=16), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('actor_kind', sa.String(length=8), nullable=False),
    sa.Column('actor_id', sa.String(length=128), nullable=False),
    sa.Column('reverts_record_id', sa.String(length=32), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reverts_record_id'], ['review_records.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_review_records_target_id'), 'review_records', ['target_id'], unique=False)
    op.create_index(op.f('ix_review_records_work_id'), 'review_records', ['work_id'], unique=False)
    op.create_table('review_states',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('target_kind', sa.String(length=8), nullable=False),
    sa.Column('target_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('updated_by', sa.String(length=128), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('target_kind', 'target_id')
    )
    op.create_index(op.f('ix_review_states_work_id'), 'review_states', ['work_id'], unique=False)
    op.create_table('current_app_import_reports',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('episode_id', sa.String(length=32), nullable=False),
    sa.Column('source_file_name', sa.Text(), nullable=False),
    sa.Column('source_sha256', sa.String(length=64), nullable=False),
    sa.Column('image_origin', sa.String(length=16), nullable=False),
    sa.Column('created_by', sa.String(length=128), nullable=False),
    sa.Column('counts', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('entries', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['episode_id'], ['episodes.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_current_app_import_reports_work_id'), 'current_app_import_reports', ['work_id'], unique=False)
    op.create_table('element_generation_settings',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('target_kind', sa.String(length=16), nullable=False),
    sa.Column('page_id', sa.String(length=32), nullable=True),
    sa.Column('panel_id', sa.String(length=32), nullable=True),
    sa.Column('image_id', sa.String(length=32), nullable=True),
    sa.Column('prompt', sa.Text(), nullable=True),
    sa.Column('negative_prompt', sa.Text(), nullable=True),
    sa.Column('source_values', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('import_report_id', sa.String(length=32), nullable=True),
    sa.Column('human_hand_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['image_id'], ['image_files.id'], ),
    sa.ForeignKeyConstraint(['import_report_id'], ['current_app_import_reports.id'], ),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['panel_id'], ['panels.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_element_generation_settings_page_id'), 'element_generation_settings', ['page_id'], unique=False)
    op.create_index(op.f('ix_element_generation_settings_panel_id'), 'element_generation_settings', ['panel_id'], unique=False)
    op.create_index(op.f('ix_element_generation_settings_work_id'), 'element_generation_settings', ['work_id'], unique=False)
    op.create_table('text_item_translations',
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('work_id', sa.String(length=32), nullable=False),
    sa.Column('page_id', sa.String(length=32), nullable=False),
    sa.Column('text_item_id', sa.String(length=32), nullable=False),
    sa.Column('language', sa.String(length=35), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('writing_direction', sa.String(length=16), nullable=True),
    sa.Column('font_size_pt', sa.Float(), nullable=True),
    sa.Column('human_hand_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['page_id'], ['pages.id'], ),
    sa.ForeignKeyConstraint(['text_item_id'], ['text_items.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['works.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('text_item_id', 'language')
    )
    op.create_index(op.f('ix_text_item_translations_page_id'), 'text_item_translations', ['page_id'], unique=False)
    op.create_index(op.f('ix_text_item_translations_text_item_id'), 'text_item_translations', ['text_item_id'], unique=False)
    op.create_index(op.f('ix_text_item_translations_work_id'), 'text_item_translations', ['work_id'], unique=False)
    op.add_column('export_runs', sa.Column('language', sa.String(length=35), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # 訳文の判断待ちは、消す表を指している（held_ai_changes.target_table は前の版で16文字に戻る）
    op.execute("DELETE FROM held_ai_changes WHERE target_table = 'text_item_translations'")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('export_runs', 'language')
    op.drop_index(op.f('ix_text_item_translations_work_id'), table_name='text_item_translations')
    op.drop_index(op.f('ix_text_item_translations_text_item_id'), table_name='text_item_translations')
    op.drop_index(op.f('ix_text_item_translations_page_id'), table_name='text_item_translations')
    op.drop_table('text_item_translations')
    op.drop_index(op.f('ix_element_generation_settings_work_id'), table_name='element_generation_settings')
    op.drop_index(op.f('ix_element_generation_settings_panel_id'), table_name='element_generation_settings')
    op.drop_index(op.f('ix_element_generation_settings_page_id'), table_name='element_generation_settings')
    op.drop_table('element_generation_settings')
    op.drop_index(op.f('ix_current_app_import_reports_work_id'), table_name='current_app_import_reports')
    op.drop_table('current_app_import_reports')
    op.drop_index(op.f('ix_review_states_work_id'), table_name='review_states')
    op.drop_table('review_states')
    op.drop_index(op.f('ix_review_records_work_id'), table_name='review_records')
    op.drop_index(op.f('ix_review_records_target_id'), table_name='review_records')
    op.drop_table('review_records')
    # ### end Alembic commands ###
